apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    "cert-manager.io/cluster-issuer": "acme-ssl-certificate-issuer-example.org"
    # # 不设置 privateKey 的话默认是 RSA 2048
    # # ZeroSSL 目前只支持 RSA 和 ECDSA
    # "cert-manager.io/private-key-algorithm": "Ed25519"
    # "cert-manager.io/private-key-algorithm": "ECDSA" # RSA, ECDSA, Ed25519
    # "cert-manager.io/private-key-size": "256" # RSA可选值:  2048, 4096, 8192; ECDSA可选值： 256, 384, 521; Ed25519 不需要设置 size
spec:
  rules:
    - host: test.example.org
  tls:
    - secretName: secret-tls
      hosts:
        - "*.example.org"
