apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-example.org-wildcard
spec:
  secretName: cert-example.org-wildcard
  issuerRef:
    name: acme-ssl-certificate-issuer-example.org
    kind: ClusterIssuer
  dnsNames:
    - "example.org"
    - "*.example.org"
  privateKey:
    # 不指定 privateKey，默认是 RSA 2048, 可选值: RSA, ECDSA, Ed25519
    # 某些组件不支持 Ed25519，某些组件 RCDSA 只支持 256, 所以为了最佳兼容性和性能，选用ECDSA 256
    # ZeroSSL 目前只支持 RSA 和 ECDSA
    algorithm: ECDSA
    # # RSA可选值:  2048, 4096, 8192; ECDSA可选值： 256, 384, 521; Ed25519 不需要设置 size
    size: 256
    rotationPolicy: Always
