apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-example.org-sub-ca
spec:
  secretName: cert-example.org-sub-ca-secret
  isCA: true
  commonName: "Sub CA for example.org"
  issuerRef:
    name: root-ca-issuer
    kind: Issuer
  privateKey:
    # 不指定 privateKey，默认是 RSA 2048, 可选值: RSA, ECDSA, Ed25519
    # ZeroSSL 目前只支持 RSA 和 ECDSA
    algorithm: ECDSA
    # # RSA可选值:  2048, 4096, 8192; ECDSA可选值： 256, 384, 521; Ed25519 不需要设置 size
    size: 256
    rotationPolicy: Always
  duration: 17520h # 2*365d
  renewBefore: 360h # 15d
  usages:
    - signing
    - digital signature
    - key encipherment
    - key agreement
    - data encipherment
    - cert sign
    - crl sign
