apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-example.org-test
spec:
  secretName: cert-example.org-test-secret
  commonName: "test.example.org"
  dnsNames:
    - "example.com"
    - "*.example.com"
  # ipAddresses:
  #   - 192.168.0.5
  isCA: false
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    name: sub-ca-example.org-issuer
    kind: ClusterIssuer
  privateKey:
    # 不指定 privateKey，默认是 RSA 2048, 可选值: RSA, ECDSA, Ed25519
    # 某些组件不支持 Ed25519，某些组件 RCDSA 只支持 256, 所以为了最佳兼容性和性能，选用ECDSA 256
    # ZeroSSL 目前只支持 RSA 和 ECDSA
    algorithm: ECDSA
    # # RSA可选值:  2048, 4096, 8192; ECDSA可选值： 256, 384, 521; Ed25519 不需要设置 size
    size: 256
    rotationPolicy: Always
  ## 证书轮换周期
  ## 2026年3月14日前：证书有效期最长为398天。
  ## 2027年3月14日前：证书有效期最长缩短至200天。
  ## 2028年3月14日前：证书有效期最长缩短至100天。
  ## 2028年3月15日后：证书有效期最长缩短至47天。
  duration: 2160h # 90d
  renewBefore: 360h # 15d
