# General resolver behavior.
bogus-nxdomain 114.114.114.114
bogus-nxdomain 119.29.29.29
bogus-nxdomain 1.12.12.12
bogus-nxdomain 120.53.53.53
bogus-nxdomain 2402:4e00::
bogus-nxdomain 223.5.5.5
bogus-nxdomain 223.6.6.6
bogus-nxdomain 2400:3200::1
bogus-nxdomain 2400:3200:baba::1
bogus-nxdomain 180.76.76.76
bogus-nxdomain 2400:da00::6666
dualstack-ip-selection yes
dualstack-ip-selection-threshold 256
log-level info
log-console yes
ca-file /etc/ssl/certs/ca-certificates.crt
