nameserver /adguard.com/default_dns_ip
nameserver /one.one.one.one/default_dns_ip
nameserver /cloudflare-dns.com/default_dns_ip
nameserver /dot.pub/default_dns_ip
nameserver /doh.pub/default_dns_ip
nameserver /dns.alidns.com/default_dns_ip
nameserver /nextdns.io/default_dns_ip
nameserver /dns.google/gfwlist
