# Special DNS
nameserver /myip.biturl.top/local_dns
nameserver /ifconfig.me/local_dns
nameserver /ifconfig.io/local_dns
nameserver /api.myip.la/local_dns
nameserver /getip.icu/local_dns
nameserver /ip.threep.top/local_dns
nameserver /ip.sb/local_dns
