domain-set -name custom_exclude_games_cdn -file /etc/smartdns/custom.d/50-exclude-games-cdn.list
domain-rules /domain-set:custom_exclude_games_cdn/ -nameserver default_dns_ip -nftset #4:-,#6:-
domain-rules /download*.epicgames.com/ -nameserver default_dns_ip -nftset #4:-,#6:-
domain-rules /cdn*.epicgames.com/ -nameserver default_dns_ip -nftset #4:-,#6:-
domain-rules /epicgames-download*.akamaized.net/ -nameserver default_dns_ip -nftset #4:-,#6:-
domain-rules /*.epicgamescdn.com.cdn.cloudflare.net/ -nameserver default_dns_ip -nftset #4:-,#6:-
domain-rules /*.discovery.steamserver.net/ -nameserver default_dns_ip -nftset #4:-,#6:-
domain-rules /dl.playstation.net/ -nameserver default_dns_ip -nftset #4:-,#6:-
domain-rules /xvcf*.xboxlive.com/ -nameserver default_dns_ip -nftset #4:-,#6:-
domain-rules /assets*.xboxlive.com/ -nameserver default_dns_ip -nftset #4:-,#6:-
domain-rules /*.cdn.blizzard.com/ -nameserver default_dns_ip -nftset #4:-,#6:-
