# Apache Traffic Server Logging Configuration

logging:
  formats:
    - name: standard
      format: "%<cqtq> %<ttms> %<chi> %<pssc> %<psql> %<cqhm> %<cquc> %<phr> %<chm>"

  logs:
    - filename: access
      format: standard
      rolling_enabled: 1
      rolling_interval_sec: 86400
      rolling_size_mb: 200
