# mirrors:
#   <REGISTRY>:
#     endpoint:
#       - https://<REGISTRY>/v2
#     rewrite:
#       "^rancher/(.*)": "mirrorproject/rancher-images/$1"
# configs:
#   <REGISTRY>:
#     auth:
#       username: <BASIC AUTH USERNAME>
#       password: <BASIC AUTH PASSWORD>
#       token: <BEARER TOKEN>
#     tls:
#       ca_file: <PATH TO SERVER CA>
#       cert_file: <PATH TO CLIENT CERT>
#       key_file: <PATH TO CLIENT KEY>
#       insecure_skip_verify: <SKIP TLS CERT VERIFICATION BOOLEAN>
mirrors:
  docker.io:
    endpoint:
      - "https://mirror.ccs.tencentyun.com"
