#!/bin/bash

RUN_USER=tools
export ROUTER_HOME=/home/router
export ROUTER_DOMAIN=home.shkits.com
ROUTER_INTERNAL_IPV4=172.23.1.10
ROUTER_DATA_ROOT_DIR=/data
ROUTER_LOG_ROOT_DIR=$ROUTER_DATA_ROOT_DIR/logs

ROUTER_IP_RULE_GOTO_DEFAULT_PRIORITY=9091

ROUTER_LOCAL_LAN_INTERFACE='{ lo, br0, enp2s0 , vlan0, enp2s0.5, tun-vbox }'
ROUTER_IPV6_RADVD_NDP_DEVICE=(enp2s0 vlan0 enp2s0.5)
#sysctl -w net.ipv6.conf.${ROUTER_IPV6_RADVD_NDP_DEVICE[@]}.proxy_ndp=1
#sysctl -w net.ipv6.conf.${ROUTER_IPV6_RADVD_NDP_DEVICE[@]}.accept_ra=2
# Edit $ROUTER_HOME/vlan/vlan-setup-bridge.sh to make sure bridge and vlan tag will be set correctly

ROUTER_INTERNAL_SERVICE_PRIVATE_PORT_TCP="53,68,80,139,443,445,853,5432,6543,6800,8080,8375,8853"
ROUTER_INTERNAL_SERVICE_PUBLIC_PORT_TCP="6096,6349,6391,6392,6393,6443,6881,6882,6883,8371,8372,8373,36000"
ROUTER_INTERNAL_SERVICE_PRIVATE_PORT_UDP="53,67,68,80,137,138,443,546,547,784,853,1900,3478,6800,8080,8375,8853,10001"
ROUTER_INTERNAL_SERVICE_PUBLIC_PORT_UDP="6096,6349,6391,6392,6393,6443,6881,6882,6883,8371,8372,8373"
ROUTER_INTERNAL_SERVICE_PORT_TCP="${ROUTER_INTERNAL_SERVICE_PRIVATE_PORT_TCP},${ROUTER_INTERNAL_SERVICE_PUBLIC_PORT_TCP}"
ROUTER_INTERNAL_SERVICE_PORT_UDP="${ROUTER_INTERNAL_SERVICE_PRIVATE_PORT_UDP},${ROUTER_INTERNAL_SERVICE_PUBLIC_PORT_UDP}"
ROUTER_INTERNAL_SERVICE_PORT_ALL="$(echo "${ROUTER_INTERNAL_SERVICE_PORT_TCP//,/ } ${ROUTER_INTERNAL_SERVICE_PORT_UDP//,/ }" | xargs -r -n 1 echo | sort -u -n)"
ROUTER_INTERNAL_SERVICE_PORT_ALL="$(echo "$ROUTER_INTERNAL_SERVICE_PORT_ALL" | tr '\n' ',' | sed -E 's;,*$;;g' | sed -E 's;^,*;;g')"
# NTP Port: 123
ROUTER_INTERNAL_DIRECTLY_VISIT_UDP_DPORT="123"
# Port list:
#   - cockpit: 443
#   - emby: 6096
#   - syncthing-relay: 6349
#   - nextcloud: 6443
#   - aria2: 6881-6883
#   - v2ray: 6371-6373
#   - AdGuard Home: 6391-6393

ROUTER_NET_LOCAL_ENABLE_V2RAY=0
# 开启ipv6时必须 ROUTER_NET_LOCAL_ENABLE_VBOX=0 , 因为ipv6不支持通过mark触发重路由
ROUTER_NET_LOCAL_ENABLE_VBOX=1
ROUTER_NET_LOCAL_ENABLE_NAT=1
ROUTER_NET_LOCAL_ENABLE_SECURITY=1

# Unifi controller
UNIFI_CONTROLLER_WEB_PORT=6543

DHCPD_IPV4_ADDRESS=()
DHCPD_IPV6_ADDRESS=()

DNSMASQ_DNS_PORT=6053
DNSMASQ_ENABLE_DNS=0
DNSMASQ_ENABLE_DHCP=1
DNSMASQ_ENABLE_IPV6_NDP=0
DNSMASQ_ENABLE_DHCP_EXCEPT_INTERFACE=(ppp0 ppp1)

VBOX_ETC_DIR=$ROUTER_HOME/etc/vbox
VBOX_DATA_DIR=$ROUTER_DATA_ROOT_DIR/vbox
VBOX_SKIP_IP_RULE_PRIORITY=8123
# 暂不支持移除自动路由功能，因为需要读取它生成的 via 172.19.0.2 dev tun-vbox src 172.19.0.1 
# VBOX_TUN_ENABLE_AUTO_ROUTE=1
VBOX_TUN_INTERFACE=tun-vbox
VBOX_TUN_TABLE_ID=2022
# 如果走sing-box默认的tun代理设置，可能会把CN ip加入排除名单，导致无法代理DNS，所以这里手动指定常用的公共DNS服务器地址
VBOX_TUN_PROXY_WHITELIST_IPV4=(119.29.29.29 1.12.12.12 120.53.53.53 223.5.5.5 223.6.6.6 180.76.76.76 114.114.114.114)
VBOX_TUN_PROXY_WHITELIST_IPV6=(2402:4e00:: 2400:3200::1 2400:3200:baba::1 2400:da00::6666)
# 最好把目标地址直接进入排除名单，避免走tun设备再回到物理设备的性能损失
VBOX_TUN_PROXY_BLACKLIST_IPV4=( )
VBOX_TUN_PROXY_BLACKLIST_IPV6=( )
VBOX_TUN_PROXY_BLACKLIST_IFNAME=(enp2s0.5)
VBOX_IP_RULE_WITH_AUTO_REDIRECT=0
GEOIP_GEOSITE_ETC_DIR=$ROUTER_HOME/etc/v2ray

SMARTDNS_ENABLE=0
SMARTDNS_DNS_PORT=6153
SMARTDNS_ETC_DIR=$ROUTER_HOME/etc/smartdns
SMARTDNS_LOG_DIR=$ROUTER_LOG_ROOT_DIR/smartdns
SMARTDNS_APPEND_CONFIGURE=""

COREDNS_ENABLE=1
COREDNS_DNS_PORT=53
NEXTDNS_PRIVATE_TLS_DOMAIN=steering.nextdns.io

CLOUDFLARE_ZERO_TRUST_TUNNEL_TOKEN=""

# Use radvd and ndp and disable NAT6
NAT_SETUP_SKIP_IPV6=1

ACMESH_SSL_DIR=$ROUTER_HOME/acme.sh/ssl
ACMESH_SSL_MAIN_DOMAIN=shkits.com
SAMBA_DATA_DIR=$ROUTER_DATA_ROOT_DIR/samba
REDIS_PRIVATE_NETWORK_NAME=local-redis
REDIS_PRIVATE_NETWORK_IP=10.85.0.251
REDIS_HOST=$ROUTER_INTERNAL_IPV4
REDIS_PORT=6379
REDIS_DATA_DIR=$ROUTER_DATA_ROOT_DIR/redis/data
POSTGRESQL_ADMIN_USER=owent
POSTGRESQL_DATA_DIR=$SAMBA_DATA_DIR/postgresql/data
POSTGRESQL_LOG_DIR=$ROUTER_LOG_ROOT_DIR/postgresql
POSTGRESQL_SHM_SIZE=1024 # MB
POSTGRESQL_MAX_CONNECTIONS=200
POSTGRESQL_PORT=5432
NEXTCLOUD_DATA_DIR=$SAMBA_DATA_DIR/nextcloud/data
NEXTCLOUD_APPS_DIR=$SAMBA_DATA_DIR/nextcloud/apps
NEXTCLOUD_ETC_DIR=$SAMBA_DATA_DIR/nextcloud/etc
NEXTCLOUD_EXTERNAL_DIR=$SAMBA_DATA_DIR/nextcloud/external
NEXTCLOUD_TEMPORARY_DIR=$SAMBA_DATA_DIR/nextcloud/temporary
NEXTCLOUD_REVERSE_ROOT_DIR=""                             # Set non empty and use fpm docker image when success
NEXTCLOUD_TRUSTED_DOMAINS=""                              # nextcloud domains and IPs
NEXTCLOUD_CACHE_OPTIONS=()                                # --network=$REDIS_PRIVATE_NETWORK_NAME -e REDIS_HOST=$REDIS_PRIVATE_NETWORK_IP -e REDIS_HOST_PORT=$REDIS_PORT -e REDIS_HOST_PASSWORD=
ONLYOFFICE_DATA_DIR=$ROUTER_DATA_ROOT_DIR/onlyoffice/data # /var/www/onlyoffice/Data
ONLYOFFICE_CACHE_DIR=$ROUTER_DATA_ROOT_DIR/onlyoffice/lib # /var/lib/onlyoffice
ONLYOFFICE_DB_DIR=$ROUTER_DATA_ROOT_DIR/onlyoffice/db     # /var/lib/postgresql
ONLYOFFICE_LOG_DIR=$ROUTER_LOG_ROOT_DIR/onlyoffice        # /var/log/onlyoffice
ONLYOFFICE_JWT_SECRET=                                    # -e JWT_SECRET=$ONLYOFFICE_JWT_SECRET
ONLYOFFICE_DB_TYPE=postgres                               # -e DB_TYPE=$ONLYOFFICE_DB_TYPE (postgres/mariadb/mysql)
ONLYOFFICE_DB_HOST=127.0.0.1                              # -e DB_HOST=$ONLYOFFICE_DB_HOST
ONLYOFFICE_DB_PORT=$POSTGRESQL_PORT                       # -e DB_PORT=$ONLYOFFICE_DB_PORT
ONLYOFFICE_DB_NAME=onlyoffice                             # -e DB_NAME=$ONLYOFFICE_DB_NAME
ONLYOFFICE_DB_USER=onlyoffice                             # -e DB_USER=$ONLYOFFICE_DB_USER
ONLYOFFICE_DB_PASSWD=                                     # -e DB_PWD=$ONLYOFFICE_DB_PASSWD
ONLYOFFICE_CACHE_OPTIONS=()                               # --network=$REDIS_PRIVATE_NETWORK_NAME -e REDIS_SERVER_HOST=$REDIS_PRIVATE_NETWORK_IP -e REDIS_SERVER_PORT=$REDIS_PORT

TPROXY_SETUP_USING_GEOIP=0
TPROXY_SETUP_IPSET=0
TPROXY_SETUP_SMARTDNS=0
TPROXY_SETUP_DNSMASQ=0
TPROXY_SETUP_COREDNS=1
TPROXY_SETUP_WITHOUT_IPV6=0

TPROXY_SETUP_COREDNS_WITH_NFTABLES=1
TPROXY_SETUP_NFTABLES=1 # Set 1 to use iptables/ebtables
TPROXY_WHITELIST_IPV4=("91.108.56.0/22" "95.161.64.0/20" "91.108.4.0/22" "91.108.8.0/22" "149.154.160.0/22" "149.154.164.0/22" "8.8.8.8" "8.8.4.4")
TPROXY_WHITELIST_IPV6=("2001:4860:4860::8888" "2001:4860:4860::8844")
TPROXY_BLACKLIST_VLAN_TAGS=(5 6)

# Syncthing
if [[ -e "$ROUTER_HOME/syncthing/configure-server.sh" ]]; then
  source "$ROUTER_HOME/syncthing/configure-server.sh"
elif [[ -e "$(dirname "$0")/syncthing/configure-server.sh" ]]; then
  source "$(dirname "$0")/syncthing/configure-server.sh"
fi

# Emby
EMBY_CONFIG_DIR="$ROUTER_DATA_ROOT_DIR/emby/config"
EMBY_DATA_MEDIA_DIR="$ROUTER_DATA_ROOT_DIR/emby/data/media"
EMBY_DATA_CACHE_DIR="$ROUTER_DATA_ROOT_DIR/emby/cache"
EMBY_DATA_EXTERNAL_DIRS=()
if [[ ! -z "$ARIA2_DATA_ROOT" ]] && [[ -e "$ARIA2_DATA_ROOT/download" ]]; then
  EMBY_DATA_EXTERNAL_DIRS=(${EMBY_DATA_EXTERNAL_DIRS[@]} "$ARIA2_DATA_ROOT/download:download")
fi

[ -e "/opt/podman" ] && export PATH="/opt/podman/bin:/opt/podman/libexec:$PATH"
export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin"

"$@"
