#!/bin/bash

# Keepalived VRRP state transition hook.
#
# Called by keepalived-main.conf/keepalived-backup.conf with one explicit state:
#   /bin/bash /etc/keepalived/notify-state.sh MASTER
#   /bin/bash /etc/keepalived/notify-state.sh BACKUP
#
# It writes a small state file for external timers and starts/stops Kea DHCP
# services when this router becomes/leaves MASTER.

set -u

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
STATE_DIR="${KEEPALIVED_STATE_DIR:-$SCRIPT_DIR/state}"
STATE_FILE="${KEEPALIVED_STATE_FILE:-$STATE_DIR/current.env}"
LOG_TAG="${KEEPALIVED_LOG_TAG:-keepalived-notify}"
MANAGE_KEA="${KEEPALIVED_MANAGE_KEA:-1}"
KEA_SERVICES="${KEEPALIVED_KEA_SERVICES:-kea-dhcp4.service kea-dhcp6.service}"
MAIL_ENV_FILE="${KEEPALIVED_MAIL_ENV_FILE:-$SCRIPT_DIR/mail.env}"

if [[ -r "$MAIL_ENV_FILE" ]]; then
  source "$MAIL_ENV_FILE"
fi

MAIL_ENABLED="${KEEPALIVED_MAIL_ENABLED:-auto}"
MAIL_COMMAND="${KEEPALIVED_MAIL_COMMAND:-mail}"
MAIL_TO="${KEEPALIVED_MAIL_TO:-}"
MAIL_SUBJECT_PREFIX="${KEEPALIVED_MAIL_SUBJECT_PREFIX:-[keepalived]}"

function log_message() {
  local level="$1"
  shift || true

  if command -v logger >/dev/null 2>&1; then
    logger -t "$LOG_TAG" -p "daemon.$level" -- "$*"
  else
    echo "[$LOG_TAG][$level] $*" >&2
  fi
}

function normalize_state() {
  local state="${1:-}"

  case "$state" in
    MASTER|master)
      echo "MASTER"
      ;;
    BACKUP|backup)
      echo "BACKUP"
      ;;
    FAULT|fault)
      echo "FAULT"
      ;;
    STOP|stop|STOPPED|stopped)
      echo "STOP"
      ;;
    *)
      echo "UNKNOWN"
      ;;
  esac
}

STATE="$(normalize_state "${1:-}")"
TYPE="${2:-}"
NAME="${3:-}"

# Also tolerate Keepalived's generic notify format: TYPE NAME STATE.
if [[ "$STATE" == "UNKNOWN" ]] && [[ -n "${3:-}" ]]; then
  STATE="$(normalize_state "$3")"
  TYPE="${1:-}"
  NAME="${2:-}"
fi

EVENT_AT="$(date -Iseconds 2>/dev/null || date '+%Y-%m-%dT%H:%M:%S%z')"
EVENT_AT_EPOCH="$(date '+%s' 2>/dev/null || echo 0)"
HOSTNAME_VALUE="$(hostname 2>/dev/null || echo unknown)"

function write_state_file() {
  local tmp_file

  mkdir -p "$STATE_DIR" || {
    log_message err "Unable to create state directory: $STATE_DIR"
    return 1
  }

  tmp_file="$STATE_FILE.tmp.$$"
  umask 022
  {
    echo "# Generated by notify-state.sh. Do not edit manually."
    printf 'STATE=%q\n' "$STATE"
    printf 'TYPE=%q\n' "$TYPE"
    printf 'NAME=%q\n' "$NAME"
    printf 'UPDATED_AT=%q\n' "$EVENT_AT"
    printf 'UPDATED_AT_EPOCH=%q\n' "$EVENT_AT_EPOCH"
    printf 'HOSTNAME=%q\n' "$HOSTNAME_VALUE"
  } > "$tmp_file" && mv -f "$tmp_file" "$STATE_FILE" && chmod 0644 "$STATE_FILE"
}

function send_state_email() {
  local recipients_raw
  local recipients
  local subject
  local mail_status=0

  if [[ "$MAIL_ENABLED" == "0" ]] || [[ "$MAIL_ENABLED" == "false" ]] || [[ "$MAIL_ENABLED" == "FALSE" ]]; then
    return 0
  fi

  if [[ -z "$MAIL_TO" ]]; then
    if [[ "$MAIL_ENABLED" == "1" ]] || [[ "$MAIL_ENABLED" == "true" ]] || [[ "$MAIL_ENABLED" == "TRUE" ]]; then
      log_message warning "mail notification is enabled but KEEPALIVED_MAIL_TO is empty"
    fi
    return 0
  fi

  if ! command -v "$MAIL_COMMAND" >/dev/null 2>&1; then
    log_message warning "$MAIL_COMMAND is unavailable; skip keepalived state email"
    return 0
  fi

  recipients_raw="${MAIL_TO//,/ }"
  read -r -a recipients <<< "$recipients_raw"
  if [[ ${#recipients[@]} -eq 0 ]]; then
    log_message warning "KEEPALIVED_MAIL_TO has no valid recipients"
    return 0
  fi

  subject="$MAIL_SUBJECT_PREFIX $HOSTNAME_VALUE state changed to $STATE"
  if {
    printf 'Keepalived state changed.\n\n'
    printf 'Host: %s\n' "$HOSTNAME_VALUE"
    printf 'State: %s\n' "$STATE"
    printf 'Type: %s\n' "$TYPE"
    printf 'Name: %s\n' "$NAME"
    printf 'Updated at: %s\n' "$EVENT_AT"
    printf 'State file: %s\n' "$STATE_FILE"
  } | "$MAIL_COMMAND" -s "$subject" "${recipients[@]}"; then
    log_message info "keepalived state email sent to $MAIL_TO via $MAIL_COMMAND default account"
  else
    mail_status=$?
    log_message warning "failed to send keepalived state email to $MAIL_TO via $MAIL_COMMAND, exit code: $mail_status"
  fi
}

ORIGIN_STATE="$(cat "$STATE_FILE" 2>/dev/null | grep '^STATE=' | cut -d= -f2- || echo "UNKNOWN")"
if write_state_file; then
  log_message info "Keepalived state changed from $ORIGIN_STATE to $STATE, state file: $STATE_FILE"
else
  log_message warning "Keepalived state changed from $ORIGIN_STATE to $STATE, but state file update failed"
fi

if [[ "$ORIGIN_STATE" != "$STATE" ]] && [[ "$STATE" != "UNKNOWN" ]]; then
  send_state_email

  if [[ "$STATE" == "MASTER" ]] && [[ -e "$SCRIPT_DIR/../../dhcp/kea-interval-reload.sh" ]]; then
    /bin/bash "$SCRIPT_DIR/../../dhcp/kea-interval-reload.sh"
  fi
fi

exit 0