# 注意不同主板的芯片不同，所以模块名可能不同，有些模块需要的内核版本比较高，请查询后设置
# - nct6687: 微星 MPG X870E CARBON WIFI/微星 MPG B650 CARBON WIFI/微星 MAG B550M MORTAR (MAX) WIFI
# - nct6775: 华硕 ROG STRIX X870E-E GAMING WIFI7 NEO/华硕 TUF GAMING B550M-PLUS (WI-FI)
# nct6687
# nct6775
# modprobe asus_ec_sensors   # 额外读出 CPU Package / VRM / 主板温度（低端主板不一定有）