# https://docs.tigera.io/calico/latest/reference/resources/ippool
# kubectl apply -f calico-lb-ippools
# kubectl get ippools
# kubectl describe ippools/default-lb-pool
---
# ipv4-pool.yaml
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: ippool-ipv4-1
spec:
  cidr: 10.100.0.0/24
  blockSize: 24
  ipipMode: CrossSubnet
  natOutgoing: true
  nodeSelector: all()
---
# ipv4-pool.yaml
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: ippool-ipv4-2
spec:
  cidr: 10.100.1.0/24
  blockSize: 24
  ipipMode: CrossSubnet
  natOutgoing: true
  nodeSelector: all()
---
# ipv6-pool.yaml
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: ippool-ipv6-1
spec:
  cidr: fd01:0:1:0a40:0064:0:0::/112
  blockSize: 112
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
---
# ipv6-pool.yaml
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: ippool-ipv6-2
spec:
  cidr: fd01:0:1:0a40:0064:0:1::/112
  blockSize: 112
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
