# 参考
# - https://docs.cilium.io/en/stable/installation/k8s-install-helm/#k8s-install-helm
# - https://docs.cilium.io/en/stable/helm-reference/
# Test:
# - kubectl apply -n cilium-test -f https://raw.githubusercontent.com/cilium/cilium/1.17.4/examples/kubernetes/connectivity-check/connectivity-check.yaml
# - kubectl get pods -n cilium-test
# - kubectl delete ns cilium-test
# 从其他插件迁移到 cilium 先把 operator.unmanagedPodWatcher.restart 改成 true，迁移完后改回false
# 修改配置: kubectl edit configmap -n kube-system cilium-config
# operator:
#   unmanagedPodWatcher:
#     restart: true # Migration: Don't restart unmigrated pods
# -- Make Cilium take ownership over the `/etc/cni/net.d` directory on the
# node, renaming all non-Cilium CNI configurations to `*.cilium_bak`.
# This ensures no Pods can be scheduled using other CNI plugins during Cilium
# agent downtime.
# 如果要使用Multus支持多接口，exclusive 要设置未false
# exclusive: true
# "native" or "tunnel"
routingMode: "native"
# enableIPv4Masquerade,enableIPv6Masquerade 和 routingMode 相关
# 如果 routingMode 是 "tunnel"，则enableIPv4Masquerade,enableIPv6Masquerade 必须开启
enableIPv4Masquerade: true
enableIPv6Masquerade: true
# Enable installation of PodCIDR routes between worker nodes if worker nodes share a common L2 network segment.
# 如果内部Pod ip对其他节点不可达，主要关闭这个选项, autoDirectNodeRoutes 必须和 ipv4NativeRoutingCIDR,ipv6NativeRoutingCIDR 搭配
autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: "10.68.0.1/10"
ipv6NativeRoutingCIDR: "fd01:0:1:a40:0:44:0:1/64"
# cni:
#   customConf: true # Migration: Don't install a CNI configuration file
#   uninstall: false # Migration: Don't remove CNI configuration on shutdown
endpointRoutes:
  enabled: true
# IPv6基本配置
ipv6:
  enabled: true
# IPv4保持启用（双栈）
ipv4:
  enabled: true
# NativeRouting 要求宿主机能够直通这些网段
# 如果使用 eni 模式，ipam.mode 也要配置为 "eni" 。ENI模式需要平台支持, AWS 下推荐eni模式
# eni:
#   enabled: true
ipam:
  mode: "cluster-pool"
  operator:
    # 单个Node的Pod数默认限制为 110 , 但是可以改大。太大也没啥意义
    # mask size - crdi <= 16, @see https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodeipam/ipam/cidrset/cidr_set.go
    # bits - ones <= maxCIDRBits(20)
    clusterPoolIPv4MaskSize: 22
    clusterPoolIPv6MaskSize: 116
    clusterPoolIPv4PodCIDRList:
      - "10.32.0.0/16"
    clusterPoolIPv6PodCIDRList:
      - "fd01:0:1:0a20:20::/104"

# 关键配置：不强制要求IPv6 PodCIDR
k8s:
  requireIPv6PodCIDR: false

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

# 替代卸载kube-proxy (https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#kube-proxy-hybrid-modes)
k8sServiceHost: "auto"
#k8sServicePort: 6443
kubeProxyReplacement: "true"
socketLB:
  enabled: true
nodePort:
  enabled: true
  enableHealthCheck: false
  # range: "30000,32767"
externalIPs:
  enabled: true
hostPort:
  enabled: true
ingressController:
  enabled: true
  # -- Set cilium ingress controller to be the default ingress controller
  # This will let cilium ingress controller route entries without ingress class set
  default: true
bpf:
  masquerade: true
  tproxy: true
  preallocateMaps: true
bpfClockProbe: true
localRedirectPolicy: true
loadBalancer:
  # acceleration使用native需要查询网卡是否支持: lspci | grep Ethernet
  # https://docs.cilium.io/en/stable/reference-guides/bpf/progtypes/#xdp-drivers
  acceleration: best-effort
  mode: hybrid

enableLBIPAM: true
# defaultLBServiceIPAM: lbipam # lbipam, nodeipam, none
