# https://docs.cilium.io/en/stable/network/l2-announcements/#l2-announcements
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: cilium-l2policy-lb
spec:
  loadBalancerIPs: true
  # externalIPs: true
  # nodeSelector:
  #   matchExpressions:
  #     - key: node-role.kubernetes.io/control-plane
  #       operator: DoesNotExist
  interfaces:
    - ens18.2
