# https://docs.cilium.io/en/stable/network/lb-ipam/
# kubectl apply -f cilium-lb-ippools.yaml
# kubectl get ippools
# kubectl describe ippools/default-lb-pool
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "default-lb-pool"
spec:
  blocks:
    - cidr: "10.100.0.0/24"
    - cidr: "fd01:0:1:0a40:0064:0:0::/112"
    - cidr: "10.100.1.0/24"
    - cidr: "fd01:0:1:0a40:0064:0:1::/112"
  # disabled: false
  # serviceSelector:
  #   matchExpressions:
  #     - {key: color, operator: In, values: [blue, cyan]}
  #   matchLabels:
  #     color: red
  #   matchLabels:
  #     "io.kubernetes.service.namespace": "tenant-a"
