#!/bin/bash

if [[ -z "$RUN_USER" ]]; then
  RUN_USER=$(id -u -n)
fi

SYNCTHING_DISCOVERY_DOMAIN=syncthing-discovery.shkits.com
SYNCTHING_DISCOVERY_LISTEN_PORT=6341
SYNCTHING_DISCOVERY_ADDRESS=https://$SYNCTHING_DISCOVERY_DOMAIN
SYNCTHING_DISCOVERY_SSL_DIR=  # directory
SYNCTHING_DISCOVERY_SSL_CERT= # file basename under $SYNCTHING_DISCOVERY_SSL_DIR
SYNCTHING_DISCOVERY_SSL_KEY=  # file basename under $SYNCTHING_DISCOVERY_SSL_DIR
SYNCTHING_RELAY_POOL_DOMAIN=syncthing-relays.shkits.com
SYNCTHING_RELAY_POOL_LISTEN_PORT=6345
SYNCTHING_RELAY_POOL_ADDRESS=https://$SYNCTHING_RELAY_POOL_DOMAIN
# Where ot find client's ip:port. Only meaningful when running behind a reverse proxy.
#   This must be passed by reverse proxy
SYNCTHING_RELAY_POOL_IP_HEADER=X-Client-Address
SYNCTHING_RELAY_SERVER_EXT_ADDRSS= # relay://xxx.xxx:6349
SYNCTHING_RELAY_SERVER_LISTEN_PORT=6349
SYNCTHING_RELAY_SERVER_STATUS_PORT=6350

if [[ "x$SYNCTHING_CLIENT_LISTEN_PORT" == "x" ]]; then
  SYNCTHING_CLIENT_LISTEN_PORT=6348
fi
SYNCTHING_CLIENT_GUI_ADDRESS=:$SYNCTHING_CLIENT_LISTEN_PORT
if [[ -z "$SYNCTHING_CLIENT_HOME_DIR" ]] && [[ ! -z "$SAMBA_DATA_DIR" ]]; then
  SYNCTHING_CLIENT_HOME_DIR="$SAMBA_DATA_DIR/syncthing"
fi

# SOURCE:TARGET
SYNCTHING_CLIENT_REPLICATE_MODE=0
if [[ $SYNCTHING_CLIENT_REPLICATE_MODE -eq 0 ]]; then
  SYNCTHING_CLIENT_EXT_DIRS=(
    "$SAMBA_DATA_DIR/rclone/onedrive:archive/onedrive"
    "$NEXTCLOUD_DATA_DIR:archive/nextcloud/data"
    "$NEXTCLOUD_APPS_DIR:archive/nextcloud/apps"
    "$NEXTCLOUD_ETC_DIR:archive/nextcloud/etc"
    "$NEXTCLOUD_EXTERNAL_DIR:archive/nextcloud/external"
    "$NEXTCLOUD_TEMPORARY_DIR:archive/nextcloud/temporary"
  )
else
  SYNCTHING_CLIENT_EXT_DIRS=(
    "$SYNCTHING_CLIENT_HOME_DIR/data/archive:archive"
  )
fi
