#!/bin/bash

if [[ -z "$RUN_USER" ]]; then
  RUN_USER=$(id -u -n)
fi

SYNCTHING_DISCOVERY_DOMAIN=syncthing-discovery.shkits.com
SYNCTHING_DISCOVERY_LISTEN_PORT=6341
SYNCTHING_DISCOVERY_ADDRESS=https://$SYNCTHING_DISCOVERY_DOMAIN
SYNCTHING_DISCOVERY_SSL_DIR=  # directory
SYNCTHING_DISCOVERY_SSL_CERT= # file basename under $SYNCTHING_DISCOVERY_SSL_DIR
SYNCTHING_DISCOVERY_SSL_KEY=  # file basename under $SYNCTHING_DISCOVERY_SSL_DIR
SYNCTHING_RELAY_POOL_DOMAIN=syncthing-relays.shkits.com
SYNCTHING_RELAY_POOL_LISTEN_PORT=6345
SYNCTHING_RELAY_POOL_ADDRESS=https://$SYNCTHING_RELAY_POOL_DOMAIN
# Where ot find client's ip:port. Only meaningful when running behind a reverse proxy.
#   This must be passed by reverse proxy
SYNCTHING_RELAY_POOL_IP_HEADER=X-Client-Address
SYNCTHING_RELAY_SERVER_LISTEN_PORT=6349
SYNCTHING_RELAY_SERVER_STATUS_PORT=6350

if [[ -z "$ROUTER_DOMAIN" ]]; then
  SYNCTHING_RELAY_SERVER_DOMAIN=syncthing-relay-node.shkits.com
else
  SYNCTHING_RELAY_SERVER_DOMAIN=$ROUTER_DOMAIN:6443
fi

SYNCTHING_CLIENT_GUI_ADDRESS=https://$SYNCTHING_RELAY_SERVER_DOMAIN/syncthing-client
if [[ ! -z "$SAMBA_DATA_DIR" ]]; then
  SYNCTHING_CLIENT_HOME_DIR="$SAMBA_DATA_DIR"
fi
