version: "3"

networks:
  internal-backend:
    external: true
  internal-frontend:
    external: true

services:
  server:
    # image: docker.io/owt5008137:latest
    image: ghcr.io/owent/caddy:latest
    container_name: caddy
    restart: unless-stopped
    networks:
      - internal-backend
      - internal-frontend
    volumes:
      - "./etc:/etc/caddy"
      - "./data/ssl:/data/ssl"
      - "./log:/var/log/caddy"
    ports:
      - "80:80"
      - "443:443"
